version: "2"

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"

python:
  install:
    - requirements: docs/requirements.txt
    # Install our python package before building the docs
    - method: pip
      path: .

# Define the theme section and specify the logo URL
theme:
  logo:
    url: docs/source/logo_relAI.png

sphinx:
  fail_on_warning: false
